apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: muescheli
  labels:
    app: muescheli
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      # set to 0 to make sure that there is no downtime on a deployment update
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: muescheli
        release: muescheli
    spec:
      imagePullSecrets:
        - name: monoregistry
      containers:
        - name: muescheli
          image: "saikatharryc/muescheli"
          imagePullPolicy: Always
          env:
          - name: CLAMD_HOST
            value: localhost
          - name: CLAMD_PORT
            value: '3310'
          ports:
            - containerPort: 8091
        - name: clamd
          image: "lastops/clamav"
          imagePullPolicy: Always
          ports:
          - containerPort: 3310
            name: api
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: muescheli
  labels:
    app: muescheli
spec:
  type: NodePort
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: muescheli
  selector:
    app: muescheli
    release: muescheli
