name: check PR

on: [ pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]
    name: Go ${{ matrix.go }} Build
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: |
          if [ -d $GOPATH/src ]; then
          mkdir $GOPATH/src
          fi
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          fi
      - name: Build The Application
        run: go build -v .
      